export const TECHS = [
  {
    name: "HTML",
    stack: "frontend",
    image: "/techs/html.svg",
    resource_url: "https://developer.mozilla.org/es/docs/Web/HTML",
  },
  {
    name: "CSS",
    stack: "frontend",
    image: "/techs/css.svg",
    resource_url: "https://developer.mozilla.org/es/docs/Web/CSS",
  },
  {
    name: "Javascript",
    stack: "full stack",
    image: "/techs/javascript.svg",
    resource_url: "https://developer.mozilla.org/es/docs/Web/JavaScript",
  },
  {
    name: "Typescript",
    stack: "full stack",
    image: "/techs/typescript.svg",
    resource_url: "https://www.typescriptlang.org",
  },
  {
    name: "React",
    stack: "frontend",
    image: "/techs/react.svg",
    resource_url: "https://es.reactjs.org/docs/getting-started.html",
  },

  {
    name: "Next.js",
    stack: "frontend",
    image: "/techs/next-js.svg",
    resource_url: "https://nextjs.org/docs/getting-started",
  },
  {
    name: "Next PWA",
    stack: "frontend",
    image: "/techs/next-pwa.svg",
    resource_url: "https://github.com/shadowwalker/next-pwa",
  },
  {
    name: "Next Auth",
    stack: "frontend",
    image: "/techs/next-auth.svg",
    resource_url: "https://next-auth.js.org/",
  },
  {
    name: "Json WTk",
    stack: "backend",
    image: "/techs/json-wtk.svg",
    resource_url: "https://jwt.io/introduction",
  },
  {
    name: "Material-UI",
    stack: "frontend",
    image: "/techs/material-ui.svg",
    resource_url: "https://mui.com/",
  },
  {
    name: "Styled Components",
    stack: "frontend",
    image: "/techs/styled-components.svg",
    resource_url: "https://styled-components.com/",
  },
  {
    name: "Tailwind",
    stack: "frontend",
    image: "/techs/tailwind.svg",
    resource_url: "https://tailwindcss.com",
  },

  {
    name: "React Testing Library",
    stack: "testing",
    image: "/techs/react-testing-library.svg",
    resource_url:
      "https://testing-library.com/docs/react-testing-library/intro/",
  },
  {
    name: "Jest",
    stack: "testing",
    image: "/techs/jest.svg",
    resource_url: "https://jestjs.io/docs/getting-started",
  },
  {
    name: "Cypress",
    stack: "testing",
    image: "/techs/cypress.svg",
    resource_url: "https://docs.cypress.io",
  },
  {
    name: "Apollo GraphQL",
    stack: "fullstack",
    image: "/techs/graphql.svg",
    resource_url: "https://www.apollographql.com/docs/react",
  },
  {
    name: "Node.js",
    stack: "backend",
    image: "/techs/nodejs.svg",
    resource_url: "https://nodejs.org/es/docs",
  },
  {
    name: "Express",
    stack: "backend",
    image: "/techs/express.svg",
    resource_url: "https://expressjs.com/",
  },
  {
    name: "MongoDB",
    stack: "backend",
    image: "/techs/mongodb.svg",
    resource_url: "https://docs.mongodb.com",
  },
  {
    name: "Mongoose",
    stack: "backend",
    image: "/techs/mongoose.svg",
    resource_url: "https://mongoosejs.com/",
  },
  {
    name: "PostgreSQL",
    stack: "backend",
    image: "/techs/postgresql.svg",
    resource_url: "https://www.postgresql.org/docs",
  },
  {
    name: "Prisma",
    stack: "backend",
    image: "/techs/prisma-3.svg",
    resource_url: "https://www.prisma.io/docs",
  },
  {
    name: "Socket.io",
    stack: "fullstack",
    image: "/techs/socket-io.svg",
    resource_url: "https://socket.io/docs/v4",
  },
  {
    name: "Cloudinary",
    stack: "backend",
    image: "/techs/cloudinary.svg",
    resource_url: "https://cloudinary.com/documentation",
  },
  {
    name: "Nodemailer ",
    stack: "backend",
    image: "/techs/nodemailer.svg",
    resource_url: "https://nodemailer.com/about",
  },
  {
    name: "Google Cloud Console ",
    stack: "backend",
    image: "/techs/google-cloud-console.svg",
    resource_url: "https://console.cloud.google.com/",
  },
  {
    name: "vercel",
    stack: "backend",
    image: "/techs/vercel.svg",
    resource_url: "https://vercel.com",
  },
  {
    name: "Heroku",
    stack: "backend",
    image: "/techs/heroku.svg",
    resource_url: "https://www.heroku.com",
  },
  {
    name: "Git",
    stack: "fullstack",
    image: "/techs/git.svg",
    resource_url: "https://git-scm.com/doc",
  },
  {
    name: "NPM",
    stack: "fullstack",
    image: "/techs/npm.svg",
    resource_url: "https://docs.npmjs.com/",
  },
];
export const PROJECTS = [
  {
    name: "hotel room booking app",
    captions: [
      "https://res.cloudinary.com/myproyects/image/upload/v1642998067/proyects/target_2_aqjj3g.png",
      "https://res.cloudinary.com/myproyects/image/upload/c_thumb,g_north,h_398,w_710/v1642707470/proyects/screencapture-localhost-3000-search-2022-01-15-16_48_25-min_1_gedd9m.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707488/proyects/Captura_de_pantalla_2022-01-20_155932-min_y0xpcg.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707501/proyects/screencapture-localhost-3000-room-1-2022-01-16-15_57_18-min_1_pq2is5.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707491/proyects/screencapture-localhost-3000-admin-hotel-2022-01-16-16_00_02-min_1_g7qilp.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707462/proyects/screencapture-localhost-3000-admin-hotel-bookings-2022-01-16-16_03_29-min_1_e1pbmy.png",
    ],
    summary:
      "Application for the administration and request of hotel rooms with updated information on the availability of rooms.",
    features: [
      "End to end typed code.",
      "File management from server enabled.",
      "Images upload to cloudinary.",
      "Advance Image optimization.",
      "Database seed.",
      "Client end server side authentication.",
      "Session persistence.",
      "Pagination, filtering, sorting and keyword searching of hotels.",
      "SSR and ISR.",
      "SSR cache-control haders.",
      "Dinamic layouts.",
      "Full guest, hotels, rooms and bookings management system.",
      "Multy hotels and admins suport.",
      "Push notifactions",
      "Responsive layout.",
    ],
    language: "Typescript",
    technologies: {
      frontend: ["next.js", "apollo client", "material-IU", "react-hook-form"],
      backend: [
        "apollo server",
        "postgreSQL",
        "nexus",
        "prisma",
        "cloudinary",
        "json JWT",
      ],
      hosting: "vercel",
    },
    testingUser: {
      email: "admin@hotelBooker.com",
      password: "admin",
    },
    source_code: "https://github.com/BrisaDiaz/hotel_booker_app",
    demo: "https://hotel-booker-app.vercel.app/signin",
  },
  {
    name: "wikifit app",
    captions: [
      "https://res.cloudinary.com/myproyects/image/upload/v1642998067/proyects/target_r60diw.png",
      "https://res.cloudinary.com/myproyects/image/upload/c_fill,h_398,w_710/v1643000022/proyects/screencapture-fitness-wiki-nextjs-app-vercel-app-auth-signin-2022-01-19-14_36_56-min_n6wsuu.png",
      "https://res.cloudinary.com/myproyects/image/upload/c_thumb,h_398,w_710/v1642707454/proyects/screencapture-fitness-wiki-nextjs-app-vercel-app-search-2022-01-19-14_40_16-min_lrko8u.png",

      "https://res.cloudinary.com/myproyects/image/upload/v1642708557/proyects/screencapture-localhost-3000-macros-calculator-2021-12-14-01_54_03-min_pkzts9.png",
    ],
    summary:
      "Application created to search for recipes and calculate nutritional requirements adjusted to the profile and diet of users.",
    features: [
      "Progresive web app.",
      "Keyboard accessibility.",
      "Pagination, filtering, sorting and keyword searching of recipes from Spoonacular API.",
      "Display of collection label in recipes already stored by the user.",
      "Reusable and tested components.",
      "End to end tests.",
      "Mock data.",
      "SSR and SSR convined with CSR.",
      "Full tested ARM , macros and meal size calculators with results visualización.",
      "Recipe details page.",
      "User recipes collections pages.",
      "User recipes collections management system.",
      "Pages with meta data.",
      "Real time form validation.",
      "Loading indicators.",
      "Protected routes.",
      "Conditional content.",
      "Social signIn.",
      "Database coneccion.",
      "Server side authentication.",
      "Custom hooks.",
      "Responsive layout.",
    ],
    language: "javascript",
    technologies: {
      frontend: [
        "next.js",
        "next auth",
        "next-pwa",
        "tailwind",
        "react-hook-form",
      ],
      backend: ["postgreSQL", "prisma"],
      testing: ["react testing library", "jest", "cypress"],
      hosting: "vercel",
    },
    testingUser: {
      email: "admin@email.com",
      password: "admin",
    },
    source_code: "https://github.com/BrisaDiaz/fitness-wiki-nextjs-app",
    demo: "https://fitness-wiki-nextjs-app.vercel.app",
  },
  {
    name: "delivery app",
    captions: [
      "https://res.cloudinary.com/myproyects/image/upload/v1642998068/proyects/Group_24_xhlgbf.png",
      "https://res.cloudinary.com/myproyects/image/upload/c_thumb,g_north_east,h_398,w_710,y_690/v1642716747/proyects/lk-min_tazetv.png",
      "https://res.cloudinary.com/myproyects/image/upload/c_thumb,g_north,h_398,w_710/v1642716738/proyects/screencapture-fast-food-delivery-app-herokuapp-2022-01-20-16_58_45-min_yid3wi.png",

      "https://res.cloudinary.com/myproyects/image/upload/v1642716729/proyects/screencapture-fast-food-delivery-app-herokuapp-2022-01-20-16_59_51-min_rdnaaz.png",
      "https://res.cloudinary.com/myproyects/image/upload/c_thumb,g_north,h_398,w_710,y_1242/v1642716732/proyects/screencapture-fast-food-delivery-app-herokuapp-2022-01-20-17_01_06-min_gwnomp.png",
    ],
    summary:
      "Application created for the management of the menu online and real-time monitoring of the status of orders.",
    language: "javascript",
    features: [
      "Unit test examples.",
      "Lazy Load components and code spliting.",
      "Products and orders section skeletons.",
      "Custom Auto-played sliders with dot indicators and controls.",
      "Latest products carrucel using swiper.js librery.",
      "Navbar responsive and animated .",
      "Complete authentication system width singup/email validation/login/ forgot password support.",
      "Access to Public and Private routes base on roles.",
      "Funtional contact section with form validation.",
      "Loading modal and loading form indicators.",
      "Shopping cart.",
      "Editable User profile.",
      "Products and orders section with sorter, filter and search bar.",
      "URL able to storage the user seach pagination.",
      "Product details page.",
      "User orders tracker page.",
      "Real time order notifications.",
      "Dashboard with users, categories, orders and products management system.",
      "athentication using Jeson Web Tokens.",
      "Account validation , and functional contact form using Nodemailer and googleapis oAuth2.",
      "Accesss to api endpoints base athorization and permition.",
      "Media storage using cloudinary service.",
      "Request supported : GET, PUT, POST, DELETE.",
      "Rutes: USERS , PRODUCTS, CATEGORIES, ORDERS,NEWSLETTER, CONTACT, AUTH.",
      "Initial mongoose set up with : default categories , roles and admin and moderator users.",
    ],
    technologies: {
      frontend: [
        "react",
        "react-router-dom",
        "styled-components",
        "react-hook-form",
        "socket.io-client",
        "swiper",
      ],
      backend: [
        "node.js",
        "express",
        "mongodDB",
        "mongoose",
        "cloudinary",
        "oAuth2",
        "nodemailer",
        "socket.io",
        "jsonJWT",
      ],
      hosting: "heroku",
    },

    testingUser: {
      email: " moderator@localhost.com",
      password: "moderator",
    },
    source_code: "https://github.com/BrisaDiaz/Mern-stack-delivery-app",
    demo: "https://fast-food-delivery-app.herokuapp.com",
  },
  {
    name: "fotographer porafolio",
    captions: [
      "https://res.cloudinary.com/myproyects/image/upload/v1642998071/proyects/target_3_jhisbz.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707844/proyects/screencapture-127-0-0-1-5500-Fotographer-web-page-index-html-2022-01-18-18_06_05_k77cnh.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707974/proyects/photograph-2_a5jauh.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707495/proyects/photograph-3-min_xzau6f.png",
      "https://res.cloudinary.com/myproyects/image/upload/v1642707468/proyects/screencapture-127-0-0-1-5500-Fotographer-web-page-contacto-contact-html-2022-01-18-18_06_26-min_pixtgh.png",
    ],
    summary: "Modern and interactive web portfolio of photographic services.",
    language: "javascript",
    technologies: {
      frontend: ["vanilla javascript", "css", "html"],
      hosting: "github pages",
    },
    features: [
      `Modularized javaScript code.`,
      `Responsive desing.`,
      `Proyects gallery with hover effect and animated zoom modal.`,
      `On scroll animations.`,
      `Auto-played slider with clients testimonials.`,
      `Skill progress bars.`,
      `counters of Achievements.`,
      `Drop-down FAQ list.`,
      `Animated menu nav.`,
      `Contact page with Form validation.`,
      `Smooth scroll to top button.`,
    ],
    source_code: "https://github.com/BrisaDiaz/Fotographer_web_page",
    demo: "https://brisadiaz.github.io/Fotographer_web_page",
  },
];
export const SKILLS = [
  "Strong proficiency in JavaScript and DOM manipulation.",
  "Experience integrating Typescript in a medium size project.",
  "Expertise in creating responsive UI implementations.",
  "Experiance implementing keyboard accessibilitye.",
  "Experience in creating and integrating REST and GraphQL APIs.",
  "Experience with Unit Testing and End to End testing.",
  "Experience implementing rendering techniques like SSG, SSR and ISR.",
  "Experience in configuration of the dependencies and mangment of compatibility issues.",
  "Knowledge in design patterns and modularization.",
  "First hand knowledge of the work of a web designer and a back-end developer.",
  "Ability of tracking bugs, detecting bad practices and correcting them right away.",
  "Ability to quickly become familiar with new technologies.",
  "Ability to work autonomously and be proactive.",
  "Intermediate written and spoken english proficiency.",
];
